In [74]:
import os
import warnings
import numpy as np
import nibabel as nib
from Orientation import orientate_base_images

oriented_ref = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data','Reoriented Base Images (R_)','R_321_FLAIR<=T2_Flair_Axial_p2_5.nii')
resampled_attempt = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data','Resampled Images','R_321_FLAIR<=T2_Flair_Axial_p2_5.nii')
base = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data','Base Images','321_FLAIR<=T2_Flair_Axial_p2_5.nii')
ref = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data','Reference Images (w3_)','w3_321_FLAIR<=T2_Flair_Axial_p2_5.nii')


oriented_img = nib.load(oriented_ref)
resampled_img = nib.load(resampled_attempt)
base_img = nib.load(base)
ref_img = nib.load(ref)




base_img.shape

(232, 256, 28)

In [75]:
affine_oriented = oriented_img.affine
affine_resampled = resampled_img.affine
affine_base = base_img.affine
print(affine_oriented)
print(affine_resampled)
print('\n')
print(affine_base)

[[-8.59375000e-01  1.76260742e-10 -2.32475313e-16  9.96875000e+01]
 [ 1.73309242e-10  8.44984710e-01 -1.09341311e+00  3.91958191e+02]
 [ 3.21209344e-11  1.56608656e-01  5.89952946e+00  1.33387165e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 2.00000000e+00 -4.10206813e-10  7.73506517e-17 -9.88281250e+01]
 [-4.03337863e-10 -1.96650982e+00  3.64471048e-01  1.07436035e+02]
 [-7.47541751e-11 -3.64471048e-01 -1.96650982e+00  1.72626007e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[[-8.59375000e-01 -1.76260742e-10 -2.32475313e-16  9.96875000e+01]
 [ 1.73309242e-10 -8.44984710e-01 -1.09341311e+00  1.36958191e+02]
 [ 3.21209344e-11 -1.56608656e-01  5.89952946e+00  1.33387165e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [21]:
3.91958191e+02 - 1.36958191e+02

255.0

In [65]:
header_oriented = oriented_img.header
header_resampled = resampled_img.header
print(header_oriented)
print(header_resampled)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 232 256  28   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float64
bitpix          : 64
slice_start     : 0
pixdim          : [-1.        0.859375  0.859375  6.        1.        1.        1.
  1.      ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : -1.0212149e-10
quatern_c       : -0.9958049
quatern_d       : -0.091501616
qoffset_x       : 99.6875
qoffset_y       :

In [66]:
sx, sy, sz = oriented_img.header.get_zooms()
tx, ty, tz = base_img.header.get_zooms()
zx, zy, zz = ref_img.header.get_zooms()
print(sx,sy,sz)
print(tx,ty,tz)
print(zx,zy,zz)

0.859375 0.859375 6.0
0.859375 0.859375 6.0
2.0 2.0 2.0


In [31]:
import os
import warnings
import numpy as np
import nibabel as nib
from Orientation import orientate_base_images

import monai
from monai.data import Dataset, DataLoader
from monai.transforms import (
    LoadImage,
    EnsureChannelFirst,
    Orientation,
    Spacing,
    Compose,
    SaveImage,
    ToTensor,
)
#help(Compose)

In [24]:
import nibabel as nib

# Load the NIfTI file

file_path = '/Users/theochiang/Documents/MATLAB/spm-main/tpm/TPM.nii'
nifti_file = nib.load(file_path)

# Get the affine matrix
affine = nifti_file.affine

# Determine the orientation of the NIfTI file
orientation = nib.aff2axcodes(affine)

# Print the orientation
print(f"The orientation of the NIfTI file is: {orientation}")

The orientation of the NIfTI file is: ('L', 'A', 'S')


In [25]:
transform = nib.orientations.ornt_transform(
            nib.orientations.axcodes2ornt(('R','A','S')),
            nib.orientations.axcodes2ornt(('L','A','S'))
        )
transform

array([[ 0., -1.],
       [ 1.,  1.],
       [ 2.,  1.]])

In [32]:
2/.859375

2.327272727272727

In [42]:
print(affine_base)
print('\n')
def print_affine_matrix(matrix):
    print("[")
    for row in matrix:
        formatted_row = " ".join([f"{item: .10e}" for item in row])
        print(f"[{formatted_row}]")
    print("]")

# Example matrix
affine_matrix = np.array([
    [-8.59375000e-01, -1.76260742e-10, -2.32475313e-16,  9.96875000e+01],
 [ 1.73309242e-10, -8.44984710e-01, -1.09341311e+00,  1.36958191e+02],
 [ 3.21209344e-11, -1.56608656e-01,  5.89952946e+00,  1.33387165e+01],
 [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]
])

# Print the affine matrix using the print function
print_affine_matrix(affine_matrix)


[[-8.59375000e-01 -1.76260742e-10 -2.32475313e-16  9.96875000e+01]
 [ 1.73309242e-10 -8.44984710e-01 -1.09341311e+00  1.36958191e+02]
 [ 3.21209344e-11 -1.56608656e-01  5.89952946e+00  1.33387165e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


[
[-8.5937500000e-01 -1.7626074200e-10 -2.3247531300e-16  9.9687500000e+01]
[ 1.7330924200e-10 -8.4498471000e-01 -1.0934131100e+00  1.3695819100e+02]
[ 3.2120934400e-11 -1.5660865600e-01  5.8995294600e+00  1.3338716500e+01]
[ 0.0000000000e+00  0.0000000000e+00  0.0000000000e+00  1.0000000000e+00]
]


In [43]:
import os
import warnings
import nibabel as nib
import numpy as np

# Suppress the specific deprecation warning
warnings.filterwarnings("ignore", message=".*`torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.*")

# Define paths
data_dir = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data')
base_image_paths = [os.path.join(data_dir, 'Base Images', f) for f in os.listdir(os.path.join(data_dir, 'Base Images')) if f.endswith(('.nii', '.nii.gz'))]
reference_image_paths = [os.path.join(data_dir, 'Reference Images (w3_)', f) for f in os.listdir(os.path.join(data_dir, 'Reference Images (w3_)')) if f.endswith(('.nii', '.nii.gz'))]

def check_orientation_and_spacing(base_image_path, reference_image_path):
    base_img = nib.load(base_image_path)
    ref_img = nib.load(reference_image_path)
    
    # Check orientation
    base_orientation = nib.aff2axcodes(base_img.affine)
    ref_orientation = nib.aff2axcodes(ref_img.affine)
    
    # Check voxel spacing
    base_spacing = np.sqrt(np.sum(base_img.affine[:3, :3] ** 2, axis=0))
    ref_spacing = np.sqrt(np.sum(ref_img.affine[:3, :3] ** 2, axis=0))
    
    same_orientation = base_orientation == ref_orientation
    same_spacing = np.allclose(base_spacing, ref_spacing)
    
    return same_orientation, same_spacing

# Iterate over the base and reference images to compare their orientation and spacing
for base_image_path, reference_image_path in zip(base_image_paths, reference_image_paths):
    same_orientation, same_spacing = check_orientation_and_spacing(base_image_path, reference_image_path)
    
    print(f"Comparing {os.path.basename(base_image_path)} with {os.path.basename(reference_image_path)}:")
    print(f"  Same Orientation: {'Yes' if same_orientation else 'No'}")
    print(f"  Same Voxel Spacing: {'Yes' if same_spacing else 'No'}")
    print()


Comparing 384_FLAIR<=AX_FLAIR_5.nii with w3_340_FLAIR<=AX_FLAIR_5.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 378_FLAIR<=AX_FLAIR_5.nii with w3_384_FLAIR<=AX_FLAIR_5.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 462_FLAIR<=AX_FLAIR_6.nii with w3_426_FLAIR<=T2_Flair_Axial_p2_8.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 370_FLAIR<=T2_Flair_Axial_p2_5.nii with w3_462_FLAIR<=AX_FLAIR_6.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 340_FLAIR<=AX_FLAIR_5.nii with w3_378_FLAIR<=AX_FLAIR_5.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 358_FLAIR<=AX_FLAIR_5.nii with w3_431_FLAIR<=T2_Flair_Axial_p2_6.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 458_FLAIR<=T2_Flair_Axial_p2_5.nii with w3_466_FLAIR<=AX_FLAIR_3.nii:
  Same Orientation: No
  Same Voxel Spacing: No

Comparing 390_FLAIR<=T2_Flair_Axial_p2_5.nii with w3_459_FLAIR<=T2_Flair_Axial_p2_8.nii:
  Same Orientation: No
  Same Voxel

In [53]:
import os
import warnings
import numpy as np
import nibabel as nib
#from nonfunctional-Orientation import orientate_base_images

import monai
from monai.data import Dataset, DataLoader
from monai.transforms import (
    LoadImage,
    EnsureChannelFirst,
    Orientation,
    Spacing,
    Compose,
    SaveImage,
    ToTensor,
)

# Suppress the specific deprecation warning
warnings.filterwarnings("ignore", message=".*`torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.*")


# Define paths
data_dir = os.path.join(os.path.expanduser("~"), 'Desktop', 'Radiology Internship 2024', 'python code', 'Registration_Torch_Model_Chiang', 'Training Data')
base_image_paths = [os.path.join(data_dir, 'Base Images', f) for f in os.listdir(os.path.join(data_dir, 'Base Images')) if f.endswith(('.nii', '.nii.gz'))]

reference_image_paths = [os.path.join(data_dir, 'Reference Images (w3_)', f) for f in os.listdir(os.path.join(data_dir, 'Reference Images (w3_)')) if f.endswith(('.nii', '.nii.gz'))]








#FUNCTIONS:

def print_transforms(transformations):
    print("Contents of the Compose object:")
    for i, transform in enumerate(transformations.transforms):
        print(f"Transform {i + 1}: {transform}")

def update_affine(og_affine, transforms, base_spacing):
    #ASSUMES REORIENTATION AND VOXEL CHANGE
    spacing_transform = transforms.transforms[2]
    new_spacing = spacing_transform.pixdim
    base_spacing = base_spacing
    
    
    

def find_target_spacing(reference_image_paths):
    nifti_file = nib.load(reference_image_paths[0])
    affine = nifti_file.affine
    voxel_sizes = np.sqrt(np.sum(affine[:3, :3] ** 2, axis=0))
    return(voxel_sizes)

def original_spacing(base_image_paths):
    nifti_file = nib.load(base_image_paths[0])
    affine = nifti_file.affine
    voxel_sizes = np.sqrt(np.sum(affine[:3, :3] ** 2, axis=0))
    return(voxel_sizes)

def find_target_orientation(reference_image_paths):
    nifti_file = nib.load(reference_image_paths[0])
    affine = nifti_file.affine
    target_orientation = nib.aff2axcodes(affine)
    return(target_orientation)








#Class for dataloader
class MedicalImageDataset(Dataset):
    def __init__(self, image_paths, transform=None):
        self.image_paths = image_paths
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        print(f"Loading image: {image_path}")  # Debug print to check the image path
        try:
            image = LoadImage(image_only=False)(image_path)
            image, metadata = image[0], image[1]

            print(f"Loaded image: {type(image)}")  # Debug print to check the loaded image type
            if self.transform:
                image = self.transform(image)
                print(f"Transformed image: {type(image)}")  # Debug print to check the transformed image type



            #print()

            #metadata[1]['affine'] = update_affine(metadata[1]['affine'], transforms, base_spacing)
            file_name = os.path.basename(image_path)
            return image, file_name, metadata  # Return both the transformed image and the original file name
        except Exception as e:
            print(f"Error loading image {image_path}: {e}")
            raise    

                
#MAIN CLASS
def resample(data_dir, base_image_paths, reference_image_paths):
    
    
    # Define the target spacing for resampling (e.g., 1.0mm x 1.0mm x 1.0mm)
    
    #DONT NEED TO FIND FOR EACH INDIVIDUAL IMAGE CAUSE IS THE SAME
    target_spacing = find_target_spacing(reference_image_paths)
    target_orientation = find_target_orientation(reference_image_paths)
    target_orientation = ''.join(target_orientation)
    base_spacing = original_spacing(base_image_paths)
    print("Target Orientation: " + str(target_orientation))
    print("Target Spacing: " + str(target_spacing))
    print("og Spacing: " + str(base_spacing))
    #print("Voxel spacing: " + str(target_spacing))


    
    
    # Define transforms
    transforms = Compose([
        #LoadImage(image_only=True),
        EnsureChannelFirst(),  # Ensures the channel dimension is first
        Orientation(axcodes=target_orientation),  # Reorient to RAS
        Spacing(pixdim=target_spacing, mode='bilinear'),  # Resample to target spacing
        ToTensor()
    ])



    dataset = MedicalImageDataset(base_image_paths, transform=transforms)
    dataloader = DataLoader(dataset, batch_size=1, shuffle=False)




    #REORIENT AND RESAMPLE
    resampled_dir = os.path.join(data_dir, 'Resampled Images')
    os.makedirs(resampled_dir, exist_ok=True)


    for i, (resampled_image, file_name,metadata) in enumerate(dataloader):
        resampled_image = resampled_image.squeeze().numpy()  # Remove batch dimension and convert to numpy array
        resampled_image_name = "R_" + str(file_name[0])
        resampled_image_path = os.path.join(resampled_dir, resampled_image_name)

        new_affine = metadata['affine'].squeeze().numpy()


        try:
            # Create a NIfTI image
            nifti_image = nib.Nifti1Image(resampled_image, new_affine)

            # Save the NIfTI image
            nib.save(nifti_image, resampled_image_path)
            print(f"Saved resampled image to {resampled_image_path}")
        except Exception as e:
            print(f"Error saving image {resampled_image_path}: {e}")
            raise




#call from main
resample(data_dir, base_image_paths, reference_image_paths)

Target Orientation: LAS
Target Spacing: [2. 2. 2.]
og Spacing: [0.859375   0.85937503 6.00000028]
Loading image: /Users/theochiang/Desktop/Radiology Internship 2024/python code/Registration_Torch_Model_Chiang/Training Data/Base Images/384_FLAIR<=AX_FLAIR_5.nii
Loaded image: <class 'monai.data.meta_tensor.MetaTensor'>
Transformed image: <class 'monai.data.meta_tensor.MetaTensor'>
Saved resampled image to /Users/theochiang/Desktop/Radiology Internship 2024/python code/Registration_Torch_Model_Chiang/Training Data/Resampled Images/R_384_FLAIR<=AX_FLAIR_5.nii
Loading image: /Users/theochiang/Desktop/Radiology Internship 2024/python code/Registration_Torch_Model_Chiang/Training Data/Base Images/378_FLAIR<=AX_FLAIR_5.nii
Loaded image: <class 'monai.data.meta_tensor.MetaTensor'>
Transformed image: <class 'monai.data.meta_tensor.MetaTensor'>
Saved resampled image to /Users/theochiang/Desktop/Radiology Internship 2024/python code/Registration_Torch_Model_Chiang/Training Data/Resampled Images/R_

In [59]:
for i in range(len('LAS')):
    print('LAS'[i])
    
    
'LAS'[0]

L
A
S


'L'

In [69]:
image_path = base_image_paths[1]
image = nib.load(image_path)
image_dims = image.shape
image.shape[0]

212

In [76]:
import ants
help(ants.crop_indices)

Help on function crop_indices in module ants.ops.crop_image:

crop_indices(image, lowerind, upperind)
    Create a proper ANTsImage sub-image by indexing the image with indices. 
    This is similar to but different from array sub-setting in that 
    the resulting sub-image can be decropped back into its place without 
    having to store its original index locations explicitly.
    
    ANTsR function: `cropIndices`
    
    Arguments
    ---------
    image : ANTsImage  
        image to crop
    
    lowerind : list/tuple of integers  
        vector of lower index, should be length image dimensionality
    
    upperind : list/tuple of integers
        vector of upper index, should be length image dimensionality
    
    Returns
    -------
    ANTsImage
    
    Example
    -------
    >>> import ants
    >>> fi = ants.image_read( ants.get_ants_data("r16"))
    >>> cropped = ants.crop_indices( fi, (10,10), (100,100) )
    >>> cropped = ants.smooth_image( cropped, 5 )
    >>> decr

In [73]:
base_image_paths = [os.path.join(data_dir, 'Base Images', f) for f in os.listdir(os.path.join(data_dir, 'Base Images')) if f.endswith(('.nii', '.nii.gz'))]
os.path.basename(base_image_paths[0])

'384_FLAIR<=AX_FLAIR_5.nii'

In [77]:
a = [[2,3],[5,6]]


TypeError: can only concatenate list (not "int") to list